# Generated by Django 3.2.3 on 2021-05-23 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wppApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptedPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(max_length=250)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wppApp.site')),
            ],
        ),
    ]
